# configurar el datasource
spring:
#  profile.active: prod
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

server:
  port: ${SERVER_PORT}
  error:
    include-stacktrace: never

api:
  security:
    secret: ${JWT_SECRET}