# configurar el datasource
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3307}/vollmed_api?createDatabaseIfNotExist=true
    username: ${DB_MYSQL_USER:admin}
    password: ${DB_MYSQL_PASS:admin}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#    hibernate:
#      ddl-auto: update
server:
  port: ${SERVER_PORT:8080}
  error:
    include-stacktrace: never

api:
  security:
    secret: ${JWT_SECRET:secret}
