# configurar el datasource
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3307}/vollmed_api_test?createDatabaseIfNotExist=true
    username: ${DB_MYSQL_USER:admin}
    password: ${DB_MYSQL_PASS:admin}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#    hibernate:
#      ddl-auto: update
